<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLarxf9w\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLarxf9w/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLarxf9w.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLarxf9w\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLarxf9w\appProdProjectContainer([
    'container.build_hash' => 'Larxf9w',
    'container.build_id' => '80a6442e',
    'container.build_time' => 1601200987,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLarxf9w');
